from turtle import *
x=int(input("jak velké do x? "))
y=int(input("jak velké do y? "))
up()
left(180)
forward(300)
left(180)
down()
for _ in range(y):
    for _ in range(x):
        for _ in range(6):
            forward(50)
            left(60)
        forward(50)
        left(60)
        forward(50)
        right(60)
    right(120)
    for _ in range(x):
            forward(50)
            right(60)
            forward(50)
            left(60)
    left(120)
    forward(50)
    right(60)
    up()
    forward(50)
    left(60)
    down()
exitonclick()